-- @generated by purescript-rsc -- do not edit
module Route where

import Prelude
import Next.Route (class IsRoute)

data Route = Home | Privacy | SdfLab

derive instance Eq Route
derive instance Ord Route

instance IsRoute Route where
  toPath = case _ of
    Home -> "/"
    Privacy -> "/privacy"
    SdfLab -> "/sdf-lab"
